spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

---
spring:
  profiles: localhost
  cloud:
    config:
      uri : http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 123456

eureka:
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
    client:
       service-url:
          default-zone: http://localhost:8761/eureka/